[package]
name = "aqueducts-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
aqueducts = { path = "../aqueducts/core", features = ["s3", "gcs", "azure"] }
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
log = "0.4.21"
tokio = { version = "1.37.0", features = ["full"] }

[[bin]]
name = "aqueducts"
path = "src/main.rs"
