[package]
name = "aqueducts-cli"
authors = ["<michelevig@protonmail.com>"]
edition = "2021"
description = "CLI application to run pipelines defined for the aqueducts framework"
homepage = "https://github.com/vigimite/aqueducts"
repository = "https://github.com/vigimite/aqueducts/aqueducts-cli"
readme = "../README.md"
version = "0.1.0"
keywords = ["aqueducts", "ETL", "data", "pipeline", "cli"]
categories = ["command-line-utilities"]
license-file = "../LICENSE"

[dependencies]
aqueducts = { path = "../aqueducts/core", version = "0.1", features = ["s3", "gcs", "azure"] }
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
log = "0.4.21"
tokio = { version = "1.37.0", features = ["full"] }

[[bin]]
name = "aqueducts"
path = "src/main.rs"
